---
version: "3.6"
services:
  server:
    image: ${COMPOSE_PROJECT_NAME}_server
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_HOST: database
      MYSQL_USER: helferinnensystem
      MYSQL_PASSWORD: helferinnensystem
      MYSQL_DATABASE: helferinnensystem
      APP_NAME: Helferinnensystem
      CONTACT_EMAIL: "mailto:helfen@froscon.org"
      THEME: 0
      TSHIRT_SIZE_REQUIRED: 'false'
      ANGEL_AUTOARRIVE: 'true'
      SUPPORTERS_CAN_PROMOTE: 'true'
      SIGNUP_POST_FRACTION: 1
      PASSWORD_MINIMUM_LENGTH: 5
      ENABLE_PLANNED_ARRIVAL: 'false'
      ENABLE_FORCE_ACTIVE: 'false'
      GOODIE_TYPE: none
      ENABLE_VOUCHER: 'false'
      NIGHT_SHIFTS: 'false'
      IFSG_ENABLED: 'true'
      IFSG_LIGHT_ENABLED: 'true'
      DEFAULT_LOCALE: de_DE
    ports:
      - "5080:80"
    env_file: deployment.env
    networks:
      - database
      - internet
    depends_on:
      - database
  database:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: helferinnensystem
      MYSQL_USER: helferinnensystem
      MYSQL_PASSWORD: helferinnensystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
  backup:
    image: ${COMPOSE_PROJECT_NAME}_backup
    build:
      context: ..
      dockerfile: docker/backup.Dockerfile
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    networks:
      - database
    volumes:
      - backup:/backup
    secrets:
      - db_root_password
volumes:
  db: {}
  backup: {}

networks:
  database:
    internal: true
  internet:
