---
version: "3.6"
services:
  es_nginx:
    image: es_nginx
    build:
      context: ..
      dockerfile: docker/nginx/Dockerfile
    ports:
      - 5000:80
    networks:
      - fpm
      - internet
    depends_on:
      - es_php_fpm
  es_php_fpm:
    image: es_php_fpm
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      MYSQL_HOST: es_database
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_DATABASE: engelsystem
    # some optional env vars and their defaults can be seen in the env file
    # for exact information have a look at config/config.default.php
    env_file: deployment.env
    networks:
      - database
      - fpm
      - internet
    depends_on:
      - es_database
  es_database:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: engelsystem
      MYSQL_USER: engelsystem
      MYSQL_PASSWORD: engelsystem
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: "yes"
    volumes:
      - db:/var/lib/mysql
    networks:
      - database
volumes:
  db: {}

networks:
  database:
    internal: true
  fpm:
    internal: true
  internet:
